---
version: 2.1
jobs:
    build:
        resource_class: large
        docker:
            - image: us.gcr.io/lumen5-170819/circleci:jdk8
              auth:
                  username: _json_key
                  password: $GCLOUD_DEV_KEY
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - mvn-v1-{{ .Branch }}-{{ checksum "core/pom.xml" }}
                      - mvn-v1-{{ .Branch }}-
                      - mvn-v1-
            - run:
                  name: Make Distribution
                  command: |
                      ./dev/make-distribution.sh \
                          --name lumen5-spark \
                          --pip \
                          --tgz \
                          -Phadoop-2.7 \
                          -Phive \
                          -Phive-thriftserver \
                          -Pmesos \
                          -Pyarn \
                          -Pkubernetes
            - restore_cache:
                  paths:
                      - /root/.m2
                  key: mvn-v1-{{ .Branch }}-{{ checksum "core/pom.xml" }}
            - persist_to_workspace:
                  root: .
                  paths:
                      - dist
    deploy:
        docker:
            - image: docker:19.03-git
        steps:
            - setup_remote_docker:
                  docker_layer_caching: true
            - attach_workspace:
                  at: workspace
            - run: |
                  set -x
                  apk add bash
                  cd workspace/dist
                  ./bin/docker-image-tool.sh \
                      -r us.gcr.io/lumen5-170819 \
                      -t $CIRCLE_SHA1 \
                      build
workflows:
    version: 2
    build_workflow:
        jobs:
            - build:
                  filters:
                      tags:
                          ignore: /.*/  # all tags
                      branches:
                          only: /^release-2.4.3$/  # release branch
            - deploy:
                  requires:
                      - build
                  filters:
                      tags:
                          ignore: /.*/  # all tags
                      branches:
                          only: /^release-2.4.3$/  # release branch
